name: sync branch (working)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to deploy'
        required: true
        default: 'main'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Print branch name
      run: |
        echo "Deploying branch: ${{ github.event.inputs.branch }}"

    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
        ref: refs/heads/${{ github.event.inputs.branch }}  # Specify the branch to check out
		
    - name: Checkout the branch
      run: |
        echo "Before fetch all"
        pwd
        ls -al
        git fetch --all
        echo "After fetch all"
        # Check if the branch exists
        if git show-ref --quiet refs/heads/${{ github.event.inputs.branch }}; then
          echo "Branch ${{ github.event.inputs.branch }} exists."
        else
          echo "Branch ${{ github.event.inputs.branch }} does not exist."
          exit 1
        fi
    
    - name: print
      run: |
        cat hello.txt
