name: sync branch (working)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to deploy'
        required: true
        default: 'main'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Print branch name
      run: |
        echo "Deploying branch: ${{ github.event.inputs.branch }}"

    - name: Check if branch exists
      run: |
        # Fetch all branches from the remote repository
        git fetch --all

        # Define the branch to check
        #BRANCH_NAME=${{ github.event.inputs.branch }}
        #echo "branch is : ${BRANCH_NAME}"
        # Check if the branch exists
        if git show-ref --quiet refs/heads/${{ github.event.inputs.branch }}; then
          echo "Branch ${{ github.event.inputs.branch }} exists."
        else
          echo "Branch ${{ github.event.inputs.branch }} does not exist."
          exit 1
        fi
          
    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
        ref: refs/heads/${{ github.event.inputs.branch }}  # Specify the branch to check out
    
    - name: print
      run: |
        cat hello.txt
